FROM swr.cn-north-1.myhuaweicloud.com/codeci/special_base_image:centos7-base-1.0.2
USER build
cd /usr/local/src/
wget https://download.oracle.com/java/20/latest/jdk-20_linux-x64_bin.rpm
# yum 安装
yum install -y jdk-20_linux-x64_bin.rpm
# rpm -ivh jdk-8u291-linux-x64.rpm
